version: '3'

services:
  app:
    image: node:lts # バージョン指定も可能 ex. node:12.16.1
    container_name: todoapp
    tty: true
    stdin_open: true
    ports:
      - 3001:3000
    volumes:
      - .:/todoapp
    working_dir: "/todoapp"