version: '3'

services:
  app:
    image: node:lts # バージョン指定も可能 ex. node:12.16.1
    container_name: nodecli
    tty: true
    stdin_open: true
    volumes:
      - .:/nodecli
    working_dir: "/nodecli"